### ISSUE TITLE
In case github not return email [share]

### ISSUE THREAD

**Issue by hilmanski** [danilopolani/gocialite#11]
Not all API in github will return user's email, when the user chose the email publicity to false in their profile.

If you still need the user's email , you can access the other endpoint https://developer.github.com/v3/users/emails/

//Code example

Inside callbackhandler method:
```
`
type TheResp struct{
    Email string `json:"email"`
}

//Get Github Email if not directly sho
    if provider == "github" && user.Email == "<nil>" {
        apiRes, err := http.Get("https://api.github.com/user/emails?access_token=" + token.AccessToken)
        if err != nil {
            fmt.Printf("The HTTP request failed with error %s\n", err)
        }

        var userResp []TheResp
        json.NewDecoder(apiRes.Body).Decode(&userResp)
        fmt.Println(userResp[0].Email)
    }`
```

**Comment by danilopolani** [comment]
Hi @hilmanrdn ,
thank you for your suggestion, I'll look into it asap, obviously feel free to create a PR if you want :)
