### ISSUE TITLE
Real world usage

### ISSUE THREAD

**Issue by josephbuchma** [danilopolani/gocialite#3]
API does not seem to be suited for real world applications. Can you provide example that will work for 1000 oauth requests issued at the same time by different users ?
Global `Gocial` instance, as in your examples - is not an option in such case. Or am I missing something?

**Comment by josephbuchma** [comment]
Furthermore, users of current master are vulnerable to CSRF attacks

**Comment by danilopolani** [comment]
You're right about the CSRF attacks, I saw the PR and I'll answer below it.
After fixing the state, I think I'll write a test with 5 connections together to check it out - just five iFrames with button clicked as the same time. They are not 1000, but 1000 connections in the same exact time (milliseconds) are improbable

**Comment by josephbuchma** [comment]
@danilopolani it does not matter if it 1000 or 2 connections, such thing must be thread-safe. Run tests with race detector.

**Comment by danilopolani** [comment]
Thank you for the PR @josephbuchma , I suppose now we can close the issue, am I right?

**Comment by josephbuchma** [comment]
regarding this:
https://github.com/danilopolani/gocialite/commit/56fbaa8ee97eb5ea2a08409f9de87fed4770bd75

It does not solve the issue when using single global Gocialite instance. Once `state` has been set, it will be the same for all requests,  so I login once, capture the `state` token, and then I can compromise the rest of requests. You can regenerate `state` on each 'Handle' call, but it will completely break it's multi-threaded operability.
The only feasible way around here is to declare private global instance of something like Dispatcher and handle all this stuff implicitly, but it's shitty design. 
The best way I see here is to freeze and deprecate current api, and move towards v2.

**Comment by danilopolani** [comment]
I merged your PR of the Dispatcher and the state changes for every request, the last real commit is 785aaf64ac8c4ea830da2a52d656c4c45d0c4e4c

**Comment by josephbuchma** [comment]
I'm talking about original API, which is still available.
You should either make it impossible to use Gocial on it's own and expose it only via Dispatcher.New(), or redesign API from scratch. 
Both ways are breaking changes, and I think the latter is a better way to go.

**Comment by danilopolani** [comment]
Oh, you are talking about the `Handle`, am I right?
Well, I think I'll tag this version as v1 and the new one, without the possibility to use Gocial.Handle, as v2.

**Comment by josephbuchma** [comment]
yeah, that's the easiest way.

But I think in this way it would look much Go-ish and cleaner (which are synonyms):
```go

// initialize
gocial := gocialite.New(
    gocialite.WithProvider("facebook", fbClientID, fbClientSecret, fbRedirectURL, fbDefaultScopes),
    gocialite.WithProvider("github", ghClientID, ghClientSecret, ghRedirectURL, ghDefaultScopes),
)

// redirect
url, err := gocial.Redirect(providerName) // basic
url, err = gocial.Redirect(providerName, override, scopes, here) // override scopes

// handle
user, token, err := gocial.Handle(state, code)
```

**Comment by josephbuchma** [comment]
I also would like to change the way providers/drivers are implemented.
gocialite package should not import drivers, but rather drivers should import gocialite and register themselves (like in database/sql).
Also driver should be responsible for deserialization of response into structs.User object, so you don't have to use `reflections`. And structs package should be removed, User struct must live inside `gocialite`.

**Comment by josephbuchma** [comment]
That would be the best Go Oauth package on the internet :)

**Comment by josephbuchma** [comment]
And yes, of course, ideally Handle should also receive `context.Context`, and be cancel-able.

**Comment by danilopolani** [comment]
So, a brief recap:

- Register providers like above (example of `withProvider`, like Goth)
- Drivers should register themselves and import gocialite, not the inverse, so we can also put user struct in gocialite directly (if I do at this time, it creates a loop of imports) -> Do something with `InitializeDrivers` (personal note)
- Drivers should deserialize JSON inside the user struct, at this time gocialite does this with reflections
- Use a context

Mine goals:

- Provide a way to create a custom driver on-the-fly
- Read provider configuration from a file (JSON / YAML) -> This can avoid the registration in the `New()` method

If you don't mind, I have a question: what is the goal of context? I never used it in a personal project and I was reading [this article](https://blog.golang.org/context), in the section of **The server program**.
It uses both `context.WithCancel` and `context.WithTimeout`, but I can't understand what it does or why should it be helpful for a user.

Thank you for your help, I really appreciate it :)

**Comment by josephbuchma** [comment]
> Provide a way to create a custom driver on-the-fly

it should be possible by creating `gocialite.New(...)` on the fly, but something like `gocial.RedirectCustom(providerprops...)` is an option

> Read provider configuration from a file (JSON / YAML) -> This can avoid the registration in the New() method 

this is not really a responsibility of this package. I like how lightweight this API is, and how little assumptions it does. Nothing prevents user from assembling slice of `gocial.WithProvider(...)` calls based on configuration file that he already has in his project.

I'm glad that you're actually going hard way :)
I'll review your PR.

Regarding context, there is a lot of articles/examples of usage; it's hard to explain if few words :)

**Comment by danilopolani** [comment]
> this is not really a responsibility of this package.

Yep, you're right, my goal was to create a light package, but if doesn't require a lot of effort it could be a nice feature (but maybe never used, no one has so much providers to convince them to use an "external" configuration file instead of the `withProvider`).

Do you have any suggestion on some nice article/example/tutorial about context?
 @josephbuchma thank you a lot.
